# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mean value
#' @description Calculate the mean value using Rcpp
#' @param x a numericVector of samples
#' @return mean value \code{m}
#' @examples
#' \dontrun{
#' x<-1:100
#' meanRcpp(x)
#' }
#' @export
meanRcpp <- function(x) {
    .Call('_StatComp20094_meanRcpp', PACKAGE = 'StatComp20094', x)
}

